###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
  redis:
    image: redis:alpine

  mysql:
    image: mysql:5.7
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laraveluser
      - MYSQL_PASSWORD=laravelpass
    ports:
      - "8890:3306"
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    working_dir: /application
    volumes:
      - ./src:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8888:80"
    networks:
      - app-network

  php-fpm:
    build:
      context: ./phpdocker/php-fpm
      dockerfile: Dockerfile
      args:
        PUID: 1000
        PGID: 1000
    working_dir: /application
    volumes:
      - ./src:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
